databases:
  - name: cookingconfessions-postgres
    databaseName: cookingconfessions
    plan: free
    user: cookingconfessions

services:
  - type: web
    name: cookingconfessions-backend
    plan: free
    runtime: python
    buildCommand: "./render_build_backend.sh"
    startCommand: "poetry run gunicorn config.wsgi:application --chdir backend --limit-request-line 8188 --log-file -"
    envVars:
      - key: ENABLE_DJANGO_COLLECTSTATIC
        sync: false
      - key: AUTO_MIGRATE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cookingconfessions-postgres
          property: connectionString
      - fromGroup: python-services
      - fromGroup: integrations-credentials

envVarGroups:
  - name: python-services
    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: POETRY_VERSION
        value: 1.5.1
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
  - name: integrations-credentials
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: placeholder-value
      - key: CLOUDINARY_API_KEY
        value: apikey
      - key: CLOUDINARY_API_SECRET
        value: apikey
  - name: app-configurations
    envVars:
      - key: SITE_URL
        value: "https://cookingconfessions.onrender.com"
      - key: ADMIN_SITE_HEADER
        value: "Cooking Confessions Admin"
      - key: ADMIN_INDEX_TITLE
        value: "Cooking Confessions"
      - key: ADMIN_SITE_TITLE
        value: "Cooking Confessions"
  - name: ui-configurations
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://cookingconfessions.onrender.com/api"
      - key: NEXT_PUBLIC_API_TIMEOUT
        value: "10000"
