# Generated by Django 4.2.4 on 2023-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "New"),
                    (2, "Cooking"),
                    (3, "Packaging"),
                    (4, "On Delivery"),
                    (5, "Delivered"),
                    (6, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
