# Generated by Django 4.2.4 on 2023-11-13 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="street_address",
            new_name="address_line1",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="address_line_2",
            new_name="address_line2",
        ),
    ]
