# Generated by Django 4.2.4 on 2023-11-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_rename_street_address_customer_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_notes",
            field=models.TextField(default="", null=True),
        ),
    ]
