# Generated by Django 4.2.4 on 2023-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_order_order_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_mode",
            field=models.IntegerField(choices=[(1, "Delivery"), (2, "Pickup")], default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "Credit Card"), (2, "Cash on Delivery")], default=1
            ),
        ),
    ]
