# Generated by Django 4.2.4 on 2023-11-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_order_delivery_mode_order_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("payment_reference", models.CharField(max_length=100)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
