# Generated by Django 4.2.4 on 2023-11-21 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_orderpayments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderPayments",
            new_name="OrderPayment",
        ),
        migrations.RenameField(
            model_name="orderpayment",
            old_name="payment_reference",
            new_name="payment_refference",
        ),
    ]
