# Generated by Django 4.2.4 on 2023-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_rename_payment_refference_orderpayment_payment_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
