# Generated by Django 4.2.4 on 2023-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_alter_customer_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_line2",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
