# Generated by Django 4.2.4 on 2023-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_customer_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_notes",
            field=models.TextField(blank=True, default="-"),
            preserve_default=False,
        ),
    ]
