# Generated by Django 4.2.4 on 2023-12-25 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_alter_customer_address_line2_alter_order_order_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(choices=[(1, "Open"), (2, "Closed")], default=2)),
                ("opens_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
