# Generated by Django 4.2.4 on 2023-12-25 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_shopstatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopstatus",
            options={"verbose_name": "Shop Status", "verbose_name_plural": "Shop Status"},
        ),
    ]
