# Generated by Django 4.2.4 on 2023-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_booking_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banneritem",
            name="menu_item",
        ),
        migrations.AddField(
            model_name="banneritem",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banneritem",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banneritem",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
