# Generated by Django 4.2.4 on 2023-11-13 22:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_banneritem_menu_item_banneritem_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                help_text="Booking a past date is not allowed",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 11, 13)
                    )
                ],
            ),
        ),
    ]
