# Generated by Django 4.2.4 on 2023-11-25 09:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_booking_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                help_text="Booking a past date is not allowed",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 11, 25)
                    )
                ],
            ),
        ),
    ]
