# Generated by Django 4.2.4 on 2023-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_menuitemreview_is_visible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="sales_count",
            field=models.IntegerField(default=0),
        ),
    ]
