# Generated by Django 4.2.4 on 2023-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0006_menuitemallergen_menuitem_allergens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="allergens",
            field=models.ManyToManyField(blank=True, to="menu.menuitemallergen"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="tags",
            field=models.ManyToManyField(blank=True, to="menu.menuitemtag"),
        ),
    ]
